# Generated by Django 3.2.3 on 2021-06-20 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_store', '0002_variation'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(blank=True, to='products_store.Variation'),
        ),
    ]
