# Generated by Django 3.2.3 on 2021-06-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_store', '0003_alter_variation_variation_category'),
        ('orders', '0002_auto_20210622_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='variation',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='variations',
            field=models.ManyToManyField(blank=True, to='products_store.Variation'),
        ),
    ]
